In [5]:
import pandas as pd

result = pd.read_csv('201312.csv', encoding = 'cp949')
result

,행정구역,2013년_총인구수,2013년_세대수,2013년_세대당 인구,2013년_남자 인구수,2013년_여자 인구수,2013년_남여 비율,2014년_총인구수,2014년_세대수,2014년_세대당 인구,...,2021년_세대당 인구,2021년_남자 인구수,2021년_여자 인구수,2021년_남여 비율,2022년_총인구수,2022년_세대수,2022년_세대당 인구,2022년_남자 인구수,2022년_여자 인구수,2022년_남여 비율
0,서울특별시 (1100000000),"10,143,645","4,182,351",2.43,"5,007,869","5,135,776",0.98,"10,103,233","4,194,176",2.41,...,2.15,"4,618,040","4,891,418",0.94,"9,428,372","4,446,296",2.12,"4,570,048","4,858,324",0.94
1,서울특별시 종로구 (1111000000),"160,070","73,693",2.17,"79,519","80,551",0.99,"156,993","73,101",2.15,...,1.97,"70,183","74,500",0.94,"141,379","72,524",1.95,"68,395","72,984",0.94
2,서울특별시 중구 (1114000000),"130,465","60,600",2.15,"65,371","65,094",1.00,"128,065","59,960",2.14,...,1.93,"59,630","62,869",0.95,"120,437","63,139",1.91,"58,563","61,874",0.95
3,서울특별시 용산구 (1117000000),"239,740","109,361",2.19,"116,491","123,249",0.95,"235,951","108,429",2.18,...,2.01,"107,210","115,743",0.93,"218,650","109,805",1.99,"105,087","113,563",0.93
4,서울특별시 성동구 (1120000000),"299,337","126,447",2.37,"149,304","150,033",1.00,"296,086","125,814",2.35,...,2.13,"139,380","146,610",0.95,"281,000","133,305",2.11,"136,633","144,367",0.95
5,서울특별시 광진구 (1121500000),"368,927","159,173",2.32,"181,864","187,063",0.97,"363,354","158,524",2.29,...,2.02,"164,058","175,938",0.93,"337,416","169,291",1.99,"162,541","174,875",0.93
6,서울특별시 동대문구 (1123000000),"364,273","159,256",2.29,"182,987","181,286",1.01,"363,687","159,880",2.27,...,2.01,"166,646","170,754",0.98,"336,644","169,873",1.98,"165,755","170,889",0.97
7,서울특별시 중랑구 (1126000000),"416,798","174,938",2.38,"208,641","208,157",1.00,"418,836","176,714",2.37,...,2.09,"191,112","196,238",0.97,"385,318","187,413",2.06,"189,537","195,781",0.97
8,서울특별시 성북구 (1129000000),"476,589","196,693",2.42,"234,573","242,016",0.97,"466,706","193,359",2.41,...,2.21,"207,578","222,950",0.93,"430,397","197,082",2.18,"206,961","223,436",0.93
9,서울특별시 강북구 (1130500000),"338,707","141,246",2.40,"167,342","171,365",0.98,"335,025","141,246",2.37,...,2.07,"145,705","153,477",0.95,"293,660","144,313",2.03,"142,567","151,093",0.94
10,서울특별시 도봉구 (1132000000),"358,582","137,714",2.60,"177,153","181,429",0.98,"353,709","136,977",2.58,...,2.29,"154,487","162,879",0.95,"311,694","138,356",2.25,"151,398","160,296",0.94
11,서울특별시 노원구 (1135000000),"590,479","222,132",2.66,"288,435","302,044",0.95,"582,552","221,107",2.63,...,2.35,"246,053","264,903",0.93,"503,734","217,540",2.32,"242,145","261,589",0.93
12,서울특별시 은평구 (1138000000),"503,660","202,487",2.49,"246,858","256,802",0.96,"498,644","202,187",2.47,...,2.20,"226,458","246,849",0.92,"466,746","213,876",2.18,"222,592","244,154",0.91
13,서울특별시 서대문구 (1141000000),"314,110","135,272",2.32,"153,315","160,795",0.95,"310,376","134,780",2.30,...,2.12,"145,694","159,125",0.92,"306,337","145,797",2.10,"145,816","160,521",0.91
14,서울특별시 마포구 (1144000000),"381,856","166,780",2.29,"184,774","197,082",0.94,"385,439","169,492",2.27,...,2.05,"173,504","195,401",0.89,"364,638","180,084",2.02,"171,043","193,595",0.88
15,서울특별시 양천구 (1147000000),"492,528","180,443",2.73,"244,742","247,786",0.99,"486,221","179,069",2.72,...,2.47,"219,214","228,088",0.96,"440,881","181,187",2.43,"215,682","225,199",0.96
16,서울특별시 강서구 (1150000000),"569,070","226,607",2.51,"279,207","289,863",0.96,"585,160","234,378",2.50,...,2.12,"276,292","298,023",0.93,"569,166","273,697",2.08,"273,203","295,963",0.92
17,서울특별시 구로구 (1153000000),"424,964","171,419",2.48,"213,251","211,713",1.01,"425,831","172,594",2.47,...,2.19,"195,537","201,217",0.97,"395,315","183,655",2.15,"194,274","201,041",0.97
18,서울특별시 금천구 (1154500000),"241,020","104,179",2.31,"123,462","117,558",1.05,"238,463","103,940",2.29,...,1.96,"116,527","114,284",1.02,"229,642","119,583",1.92,"115,786","113,856",1.02
19,서울특별시 영등포구 (1156000000),"386,471","167,761",2.30,"193,880","192,591",1.01,"382,352","168,100",2.27,...,2.01,"185,926","190,911",0.97,"375,675","188,832",1.99,"184,660","191,015",0.97
20,서울특별시 동작구 (1159000000),"410,815","172,700",2.38,"202,144","208,671",0.97,"407,470","172,389",2.36,...,2.09,"186,426","199,057",0.94,"380,596","185,773",2.05,"184,030","196,566",0.94
21,서울특별시 관악구 (1162000000),"518,028","248,006",2.09,"262,248","255,780",1.03,"513,186","248,180",2.07,...,1.76,"243,991","241,708",1.01,"486,752","283,623",1.72,"244,748","242,004",1.01
22,서울특별시 서초구 (1165000000),"441,763","170,594",2.59,"213,285","228,478",0.93,"449,678","173,469",2.59,...,2.42,"197,034","215,245",0.92,"404,325","167,749",2.41,"193,159","211,166",0.91
23,서울특별시 강남구 (1168000000),"563,599","230,645",2.44,"270,601","292,998",0.92,"578,114","237,375",2.44,...,2.28,"255,047","277,995",0.92,"529,102","232,777",2.27,"253,072","276,030",0.92
24,서울특별시 송파구 (1171000000),"668,415","257,441",2.60,"326,919","341,496",0.96,"664,738","257,207",2.58,...,2.33,"317,346","340,992",0.93,"658,801","284,853",2.31,"317,180","341,621",0.93
25,서울특별시 강동구 (1174000000),"483,379","186,764",2.59,"241,503","241,876",1.00,"476,597","185,905",2.56,...,2.29,"227,002","235,662",0.96,"460,067","202,169",2.28,"225,221","234,846",0.96

In [6]:
print(result.columns)

Index(['행정구역', '2013년_총인구수', '2013년_세대수', '2013년_세대당 인구', '2013년_남자 인구수',
       '2013년_여자 인구수', '2013년_남여 비율', '2014년_총인구수', '2014년_세대수',
       '2014년_세대당 인구', '2014년_남자 인구수', '2014년_여자 인구수', '2014년_남여 비율',
       '2015년_총인구수', '2015년_세대수', '2015년_세대당 인구', '2015년_남자 인구수',
       '2015년_여자 인구수', '2015년_남여 비율', '2016년_총인구수', '2016년_세대수',
       '2016년_세대당 인구', '2016년_남자 인구수', '2016년_여자 인구수', '2016년_남여 비율',
       '2017년_총인구수', '2017년_세대수', '2017년_세대당 인구', '2017년_남자 인구수',
       '2017년_여자 인구수', '2017년_남여 비율', '2018년_총인구수', '2018년_세대수',
       '2018년_세대당 인구', '2018년_남자 인구수', '2018년_여자 인구수', '2018년_남여 비율',
       '2019년_총인구수', '2019년_세대수', '2019년_세대당 인구', '2019년_남자 인구수',
       '2019년_여자 인구수', '2019년_남여 비율', '2020년_총인구수', '2020년_세대수',
       '2020년_세대당 인구', '2020년_남자 인구수', '2020년_여자 인구수', '2020년_남여 비율',
       '2021년_총인구수', '2021년_세대수', '2021년_세대당 인구', '2021년_남자 인구수',
       '2021년_여자 인구수', '2021년_남여 비율', '2022년_총인구수', '2022년_세대수',
       '2022년_세대당 인구', '2022년_남자 인구수', '2022년_여자 인구수', '2022년_남여 비율'],
      dtype='object')

In [7]:
print(len(result.columns))

61

In [8]:
for i in range(1, len(result.columns), 6) :
    print(result.columns[i])

2013년_총인구수
2014년_총인구수
2015년_총인구수
2016년_총인구수
2017년_총인구수
2018년_총인구수
2019년_총인구수
2020년_총인구수
2021년_총인구수
2022년_총인구수

In [9]:
print(result.iloc[25])

행정구역            서울특별시 강동구 (1174000000)
2013년_총인구수                     483,379
2013년_세대수                      186,764
2013년_세대당 인구                      2.59
2013년_남자 인구수                   241,503
                         ...
2022년_세대수                      202,169
2022년_세대당 인구                      2.28
2022년_남자 인구수                   225,221
2022년_여자 인구수                   234,846
2022년_남여 비율                       0.96
Name: 25, Length: 61, dtype: object

In [10]:
print(result.iloc[25, 7])

476,597

In [11]:
print(result.iloc[25, 0])

서울특별시 강동구 (1174000000)

In [12]:
print(result.iloc[25, range(1, len(result.columns), 6)])

2013년_총인구수    483,379
2014년_총인구수    476,597
2015년_총인구수    458,658
2016년_총인구수    444,168
2017년_총인구수    436,223
2018년_총인구수    427,573
2019년_총인구수    436,067
2020년_총인구수    459,970
2021년_총인구수    462,664
2022년_총인구수    460,067
Name: 25, dtype: object

In [13]:
import pandas as pd

result = pd.read_csv('201312.csv', encoding = 'cp949')

data = {}

for i in range(1, len(result)) :
    data[result.iloc[i,0]] = result.iloc[i, range(1, len(result.columns), 6)]